name: "GeoDiff Action"
description: "GitHub Action for comparing GeoPackage/SQLite files using pygeodiff"
author: "francbartoli"
branding:
  icon: "map"
  color: "blue"

inputs:
  base_file:
    description: "Path to the GeoPackage/SQLite file. If compare_file is not provided, compares current version with the previous git commit."
    required: true
  compare_file:
    description: "Path to the file to compare against base. If not provided, base_file will be compared against its previous git commit version."
    required: false
  output_format:
    description: "Output format for the diff result (json, summary)"
    default: "json"
  summary:
    description: "Add Summary to Job"
    default: "true"
  token:
    description: "GitHub Token"
    default: ${{ github.token }}

outputs:
  diff_result:
    description: "The diff result output"
  has_changes:
    description: "Boolean indicating if changes were detected"

runs:
  using: "docker"
  image: "Dockerfile"
